Задание 4. Добавлен CI.
gpb-it-factory/shaikhutdinova-telegram-bot pull request #11
Opened 2024-05-28 21:48 UTC by GulnaraShaykh

2024-06-03 17:55 UTC, vaganov-vadim requested changes
Привет! Всё ок, но давай шаги билда и тестов разделим с заделом на будущее.

2024-06-03 17:55 UTC, vaganov-vadim commented on .github/workflows/gradle_build.yml
> +      - name: Build with Gradle Wrapper
Давай разделим шаги билда и теста. Для того чтобы запустить билд без тестов можно использовать совет Кости из чата телеграм про флаг -x.

2024-06-04 13:45 UTC, GulnaraShaykh commented on .github/workflows/gradle_build.yml
> +      - name: Build with Gradle Wrapper
о каких тестах идет речь, тут только билд без тестов

2024-06-05 16:57 UTC, vaganov-vadim approved these changes, later dismissed
Оставил пометку. Поправь и вливаем. Предварительный аппрув.

2024-06-05 16:57 UTC, vaganov-vadim commented on .github/workflows/gradle_build.yml
> +      - name: Build with Gradle Wrapper
В gradle build входят тесты :) Поэтому надо gradle build -x test

2024-06-15 14:36 UTC, GulnaraShaykh commented
@vaganov-vadim привет, посмотри плиз, все было поправлено.

2024-06-17 18:29 UTC, vaganov-vadim requested changes
Что-то пошло не так, возможно я не так направил :) Поправь, пожалуйста. Если не совсем ясно, что я имею в виду - пиши.

2024-06-17 18:29 UTC, vaganov-vadim commented on .github/workflows/gradle_build.yml
> +        run: ./gradlew build
Что-то пошло не так =) Нужен билд без тестов, а потом билд. А сейчас у нас вышло - билд с тестами, а потом под таской "тест" билд без тестов.

2024-06-21 17:51 UTC, vaganov-vadim approved these changes
Аппрув!

2024-06-21 18:11 UTC, merged